### ISSUE TITLE
CreateCollection API has problem

### ISSUE THREAD

**Issue by punitdiwan** [appwrite/sdk-for-deno#1]
In SDK the **createCollection** gives error. 

`
error: TS2322 [ERROR]: Type '{ label: string; key: string; type: string; default: string; required: true; array: false; }' is not assignable to type 'string'.
             [{ "label": "Name", "key": "name", "type": "text", "default": "Empty Name", "required": true, "array": false, } ]
`

When I here checked the signature of the method.

`async createCollection(name: string, read: Array<string>, write: Array<string>, rules: Array<string>): Promise<string> {
`

Here Rules is declared as Array of Strings. But It should be array of Objects or any Type. I have invoked the Crate Collection API like this.

`
let response = await database.createCollection(
             'Movies', // Collection Name
             ['*'], // Read permissions
             ['*'], // Write permissions
             [{
                 "label": "Name",
                 "key": "name",
                 "type": "text",
                 "default": "Empty Name",
                 "required": true,
                 "array": false,
             }
            ]     
     );
`

As this does not go with the above CreateCollection Signature. Please have a look.

Thanks
Punit

**Comment by eldadfux** [comment]
@Almoullim any chance you could help with this? We need to fix this in order to have Deno support for [Cloud Functions](https://github.com/appwrite/appwrite/issues/307). Please let me know if you don't have time, and I'll give it a go when I'm done with the Cloud Functions PR.

**Comment by Almoullim** [comment]
@eldadfux I'll check it out after work

**Comment by eldadfux** [comment]
@Almoullim thanks 🙏🏻

You can view the generated output @punitdiwan was referencing here: https://github.com/appwrite/sdk-for-deno
