### ISSUE TITLE
🐛 Bug Report: conversion.ts module not found in inputFile.ts appwrite deno sdk

### ISSUE THREAD

**Issue by MrK42** [appwrite/sdk-for-deno#11]
### 👟 Reproduction steps

Hi, I want to extend appwrite with a custom deno backend and connect via the deno sdk to appwrite.

When i start deno and the dependencies get downloaded i get the following error:
deno run --allow-net test.ts 
Warning Implicitly using latest version (0.173.0) for https://deno.land/std/streams/conversion.ts
**error: Module not found "https://deno.land/std/streams/conversion.ts".
    at https://deno.land/x/appwrite@6.2.0/src/inputFile.ts:1:42**

test.ts
```
import * as sdk from "https://deno.land/x/appwrite/mod.ts";

let client = new sdk.Client();
let databases = new sdk.Databases(client);

client
  .setEndpoint("http://localhost/v1") // Your API Endpoint
  .setProject("") // Your project ID
  .setKey("") // Your secret API key
  .setSelfSigned(); // Use only on dev mode with a self-signed SSL cert

let response = await databases.listCollections("dbId");
console.log(response);
```

I tried different appwrite sdk version and it looks like only older version will work for < 5.0.0 (3.0.0/4.0.0)
Also with a docker container it is the same issue.
```
FROM denoland/deno:1.24.3
EXPOSE 8000
WORKDIR /app
USER deno
COPY . .
RUN deno cache test.ts
CMD ["run", "--allow-all", "test.ts"]
```
I was not able to find any solution or somebody who have the same problem as me with google.
I tested the same test.ts on a M1 Mac with latest deno and appwrite sdk and the same error occurs.
Hope you can help me here.

### 👍 Expected behavior

Download all dependencies and continue

### 👎 Actual Behavior

throw error:
error: Module not found "https://deno.land/std/streams/conversion.ts".
    at https://deno.land/x/appwrite@6.2.0/src/inputFile.ts:1:42

### 🎲 Appwrite version

Different version (specify in environment)

### 🎲 Deno version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

linux: manjaro up to date

deno 1.29.4 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4

tested also other deno versions:
deno 1.24.x

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@MrK42 thanks for creating this issue! 🙏🏼 

It looks like [`conversion.ts`](https://github.com/denoland/deno_std/blob/0.172.0/streams/conversion.ts) was deprecated and removed as part of this [commit](https://github.com/denoland/deno_std/commit/a11c9570539ba7378af4b8c0727bc5ea444c5dbe).
