### ISSUE TITLE
Implement Interfaces on responses

### ISSUE THREAD

**Issue by Taha-Firoz** [appwrite/sdk-for-deno#2]
This library is useless unless we implement interfaces for the returned objects from the different functions offered by Appwrite. I understand that these were auto-generated but there must be a way we can improve and/or fix this problem.

**Comment by eldadfux** [comment]
This is something that is discussing. We are looking for ways to support this on most SDKs. I'll update when there is progress.

**Comment by TorstenDittmann** [comment]
This should be fixed by now 👍🏻
