### ISSUE TITLE
🐛 Bug Report: the definition file return for the attributes property, a list of string for the reponse of database.listAttributes in the sdk

### ISSUE THREAD

**Issue by Gi972** [appwrite/sdk-for-deno#7]
### 👟 Reproduction steps

When I 

import * as sdk from "https://deno.land/x/appwrite/mod.ts";
```

// Init SDK
let client = new sdk.Client();

let database = new sdk.Database(client);

client
    .setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2') // Your project ID
    .setKey('919c2d18fb5d4...a2ae413da83346ad2') // Your secret API key
;


let promise = database.listAttributes('[COLLECTION_ID]');

promise.then(function (response) {
    console.log(response);
}, function (error) {
    console.log(error);
});
```

### 👍 Expected behavior

I expected I have at least a object with the key in the definition 

let {total, attributes } = database.listAttributes('[COLLECTION_ID]');

where 
attributes => { key:string }[]

and even It should be

```
{ key:string 
| attributeBoolean?
| attributeInteger?
| attributeFloat?
| attributeEmail?
| attributeEnum?
| attributeUrl?
| attributeIp?
| attributeString?}[]
```

### 👎 Actual Behavior

It actually

let {total, attributes } = database.listAttributes('[COLLECTION_ID]');

I have
attributes => string[]

### 🎲 Appwrite version

Version 0.10.x

### 🎲 Deno version

Version 1.14.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
PR merged, released 🥳 Feel free to re-open the issue if you still face the problem.
